name: CD - Deploy Aws By Docker

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
          token: ${{ secrets.ACCESS_TOKEN }}
        
      # Java version 세팅
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
 
      # 도커 POSTGRESQL 이미지 실행
      - name: Create PostgreSQL Docker Container
        run: sudo docker run -d -p 5431:5432 --env POSTGRES_DB="${{ secrets.TEST_DATABASE }}" --env POSTGRES_PASSWORD="${{ secrets.TEST_DATASOURCE_PASSWORD }}" postgres:13

      - name: Grant execute permission to gradlew
        run: chmod +x ./gradlew

      # 빌드
      - name: Build with Gradle
        run: ./gradlew clean bootJar

      # 도커 로그인
      - name: Docker Build & Push to Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 빌드 후 도커 허브로 push
      - name: Docker Build & Push to Hub
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPO }} .
          docker push ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPO }}
        

      # 도커 컴포즈 실행하기
      # 도커 허브에서 jar파일 pull
      - name: Deploy to Dev
        uses: appleboy/ssh-action@master
        with:
          username: ec2-user
          host: ${{ secrets.EC2_HOST }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPO }}

            docker image prune -f
